#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
REPO_URL="https://github.com/Officiel-TinkerThink/fuel-predictor"

banner "fuel_predictor: home-server CI/CD runner setup"
say "Run this ON the home server itself (SSH into it first if you're not"
say "already there) - it checks and configures things on whatever machine"
say "it's running on."

# ── Stage 1: Docker prerequisites ──────────────────────────────────────────
stage "Check Docker is ready"
say "The deploy job will run 'docker compose' directly as the user that owns"
say "this shell, so it needs to work here without sudo."

if command -v docker >/dev/null 2>&1; then
  say "docker found: $(docker --version)"
else
  warn "docker not found. Install it first: https://docs.docker.com/engine/install/"
  exit 1
fi

if docker compose version >/dev/null 2>&1; then
  say "compose plugin found: $(docker compose version)"
else
  warn "the 'docker compose' plugin isn't available (docker-compose v1 alone isn't enough)."
  exit 1
fi

if docker ps >/dev/null 2>&1; then
  say "this user can run docker without sudo. Good."
else
  warn "running 'docker ps' failed for this user."
  step "sudo usermod -aG docker \$USER && newgrp docker"
  say "Run that, then re-run this script."
  exit 1
fi

# ── Stage 2: Deploy checkout + .env ────────────────────────────────────────
stage "Persistent deploy checkout"
say "The deploy job needs a fixed, permanent checkout of this repo on this"
say "server - it hard-resets it to origin/local on every deploy, so treat it"
say "as deploy-only: never hand-edit files in it except .env."

ask DEPLOY_PATH "Absolute path for the deploy checkout (e.g. /opt/fuel-predictor):"

if [[ -d "$DEPLOY_PATH/.git" ]]; then
  say "found an existing git checkout at $DEPLOY_PATH."
else
  if confirm "Nothing there yet - clone $REPO_URL.git into $DEPLOY_PATH now?"; then
    git clone "$REPO_URL.git" "$DEPLOY_PATH"
  else
    warn "can't continue without a checkout there. Re-run once it exists."
    exit 1
  fi
fi

git -C "$DEPLOY_PATH" fetch origin local
git -C "$DEPLOY_PATH" checkout local
git -C "$DEPLOY_PATH" reset --hard origin/local
say "checked out and reset to origin/local."

DEPLOY_ENV="$DEPLOY_PATH/.env"
if [[ -f "$DEPLOY_ENV" ]]; then
  say "$DEPLOY_ENV exists. Checking it has the values compose.prod.yaml needs..."
  missing=()
  for key in POSTGRES_PASSWORD DOMAIN ACME_EMAIL; do
    val=$(grep -E "^${key}=" "$DEPLOY_ENV" | tail -n1 | cut -d= -f2- || true)
    if [[ -z "$val" ]]; then missing+=("$key"); fi
  done
  if (( ${#missing[@]} )); then
    warn "empty or missing: ${missing[*]}"
    say "Fill these in $DEPLOY_ENV before the stack can start (see .env.example)."
    confirm "Fixed it now - continue?" || exit 1
  else
    say "POSTGRES_PASSWORD, DOMAIN, and ACME_EMAIL are all set. Not printing values - just confirming they're non-empty."
  fi
else
  warn "$DEPLOY_ENV doesn't exist yet."
  step "cp $DEPLOY_PATH/.env.example $DEPLOY_ENV"
  step "edit it: at minimum POSTGRES_PASSWORD, DOMAIN, ACME_EMAIL, and a bootstrap admin username/password."
  say "This wizard won't invent secrets for you - go fill it in, then come back."
  confirm "Done - continue?" || exit 1
fi

# ── Stage 3: Register the runner with GitHub ───────────────────────────────
stage "Register this machine as a GitHub Actions runner"
say "GitHub issues a short-lived registration token only on this page, so"
say "there's no way to script this part - copy its commands exactly."
open_url "$REPO_URL/settings/actions/runners/new"
step "Choose Linux and your architecture (x64 for most home servers)."
step "Run the 'Download' commands GitHub shows, in a working directory of your choice (e.g. ~/actions-runner)."
step "Run the './config.sh --url ... --token ...' command GitHub shows you - paste it exactly, token included."
step "When it asks for a name, something like 'fuel-predictor-home' is fine. Accept the default labels."
confirm "Runner configured (config.sh finished without error)?" || exit 1

# ── Stage 4: Install it as a service ───────────────────────────────────────
stage "Install the runner as a service"
say "Without this, the runner only listens while you keep a terminal open."
say "From the same actions-runner directory as stage 3:"
step "sudo ./svc.sh install"
step "sudo ./svc.sh start"
step "sudo ./svc.sh status   # should say 'active (running)'"
confirm "Service installed and running?" || exit 1
say "Check on GitHub too:"
open_url "$REPO_URL/settings/actions/runners"
confirm "Runner shows as 'Idle' there?" || warn "it should turn Idle within a few seconds of the service starting - check 'sudo ./svc.sh status' if not."

# ── Stage 5: Point CI at the checkout ──────────────────────────────────────
stage "Tell the workflow where the checkout lives"
say ".github/workflows/deploy.yml reads a repository variable called"
say "DEPLOY_PATH to know where to run 'docker compose' on this machine."
set_var DEPLOY_PATH "$DEPLOY_PATH"
if [[ " ${SKIPPED[*]-} " == *"DEPLOY_PATH"* ]]; then
  say "gh wasn't available/authenticated here, so set it by hand instead:"
  open_url "$REPO_URL/settings/variables/actions"
  step "New repository variable → Name: DEPLOY_PATH → Value: $DEPLOY_PATH"
  confirm "Set it?" || exit 1
fi

# ── Stage 6: Prove it end to end ───────────────────────────────────────────
stage "Dry run"
say "This runs the exact commands the deploy job runs, by hand, so you find"
say "any problem now instead of during an unattended deploy."
say ""
say "docker compose pull needs to read the image from GHCR. The deploy job"
say "authenticates itself automatically with a token GitHub provides; running"
say "this by hand, you don't have that token, so pick one:"
step "Easiest: make the package public once it exists - on the repo's main"
step "  page, right sidebar → Packages → fuel-predictor → Package settings"
step "  → Change visibility → Public. Nothing sensitive is in the image."
step "Or: 'docker login ghcr.io' with a personal access token (read:packages)."
confirm "Handled one of those?" || exit 1

say "Note: the image only exists once the build-and-push job has completed at"
say "least once - if this is the very first push of the workflow, that may"
say "still be running. Check: $REPO_URL/actions"

if confirm "Run the dry run now (cd $DEPLOY_PATH && docker compose -f compose.prod.yaml pull && up -d)?"; then
  ( cd "$DEPLOY_PATH" \
    && docker compose -f compose.prod.yaml pull \
    && docker compose -f compose.prod.yaml up -d --remove-orphans )
  say "If that started cleanly, push anything to 'local' from now on and it deploys itself."
else
  note "skipped - you can run it yourself later from $DEPLOY_PATH."
fi

finish
