#!/usr/bin/env bash
# Prepare a Codespace for the demo stack: write the .env Compose needs, then
# build the images so the first `docker compose up` is quick.
#
# Nothing here is production configuration. The credentials below exist so a
# reviewer can sign in to a throwaway Codespace; they are written to .env,
# which is not committed, and must never be reused anywhere real.
set -euo pipefail

cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists; leaving it as it is."
else
  # Compose refuses to start without POSTGRES_PASSWORD, deliberately: a
  # database password should never come from a default baked into the file.
  postgres_password="$(head -c 18 /dev/urandom | base64 | tr -d '/+=' | head -c 24)"
  cat > .env <<ENV
# Generated by .devcontainer/setup.sh for this Codespace only. Not committed.
POSTGRES_PASSWORD=${postgres_password}

# The first administrator, created when the application starts. Demo values:
# this Codespace is disposable and its ports are private to you.
FUEL_PREDICTOR_BOOTSTRAP_ADMIN_USERNAME=admin
FUEL_PREDICTOR_BOOTSTRAP_ADMIN_PASSWORD=angber-demo-2026

# Leave empty to run without Google Maps. Stops still work and the map still
# draws; only the road distance falls back to a straight-line estimate.
FUEL_PREDICTOR_GOOGLE_MAPS_API_KEY=
ENV
  echo "Wrote .env with a generated database password."
fi

echo "Building the images (a few minutes on first run)…"
docker compose build

cat <<'NEXT'

Ready. Start the stack with:

    docker compose up

Then open the forwarded port 8000 and sign in as admin / angber-demo-2026.
NEXT
